services:
  app:
    container_name: ghost_game
    build: .
    environment:
      PORT: 3000
      TEXTGEARS_API_KEY: ${TEXTGEARS_API_KEY}
    # ports:
    #   - "3000:3000"
    networks:
      - traefik-net
    labels:
      # HTTP configuration
      - "traefik.enable=true"
      - "traefik.http.routers.ghostgame.rule=Host(`ghostgame.florianurena.ovh`)"
      - "traefik.http.routers.ghostgame.entrypoints=websecure"
      - "traefik.http.routers.ghostgame.tls.certresolver=ovhdns"

networks:
  traefik-net:
    external: true